// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_idtp2hA8Bkbz_CNutRBUfK2fGcZzpqM',
    appId: '1:417966692383:android:fb592b8871322a75ee9d2a',
    messagingSenderId: '417966692383',
    projectId: 'package:zestyrentals/-70732',
    authDomain: 'package:zestyrentals/-70732.firebaseapp.com',
    storageBucket: 'package:zestyrentals/-70732.appspot.com',
    measurementId: 'G-6TCZQVPHEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_idtp2hA8Bkbz_CNutRBUfK2fGcZzpqM',
    appId: '1:417966692383:android:fb592b8871322a75ee9d2a',
    messagingSenderId: '417966692383',
    projectId: 'package:zestyrentals/-70732',
    storageBucket: 'package:zestyrentals/-70732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_idtp2hA8Bkbz_CNutRBUfK2fGcZzpqM',
    appId: '1:417966692383:android:fb592b8871322a75ee9d2a',
    messagingSenderId: '417966692383',
    projectId: 'package:zestyrentals/-70732',
    storageBucket: 'package:zestyrentals/-70732.appspot.com',
    iosClientId: '63168540332-b8snl3ggfeaosrq8acqc11npalhouus5.apps.googleusercontent.com',
    iosBundleId: 'com.package:zestyrentals/.rentals',
  );
}
